<!DOCTYPE html
   PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
    <head>
        <title><?php echo $title ?></title>
        <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <script src="../../assets/js/jquery.js"></script>
        <script src="/js/bootstrap.min.js"></script>

    <!-- Bootstrap core CSS -->
        <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
        <link href="/css/jumbotron.css" rel="stylesheet">

        <link href="/css/mentor.css" rel="stylesheet">


    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="../../assets/js/html5shiv.js"></script>
      <script src="../../assets/js/respond.min.js"></script>
    <![endif]-->
  </head>
    <body>
    <div class="navbar navbar-mentor">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://mentor.com">Mentor</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li<?php if ($section == 'home'):?> class="active" <?php endif; ?>>
                    <a href=<?php $this->url('index')?>>Home</a>
                </li>

                <?php if ($authenticated): ?>
                    <li<?php if($section == 'account'): ?> class="active"<?php endif; ?>>
                        <a href=<?php $this->url('account')?>>Account</a>
                    </li>

                    <li<?php if ($section == 'blog'): ?> class="active"<?php endif; ?>>
                      <a href=<?php $this->url('blog')?>>Blog</a>
                    </li>

                <?php else: ?>
                    <li<?php if ($section == 'register'):?> class="active"<?php endif; ?>>
                        <a href=<?php $this->url('account', array('action' =>'register'))?>>Register</a>
                    </li>
                    <li<?php if($section == 'login'):?> class="active"<?php endif; ?>>
                        <a href=<?php $this->url('account', array('action' => 'login'))?>>Login</a>
                    </li>
                <?php endif;?> 

                <!--li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li-->
          </ul>

            <!--ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{$identity->first_name|escape} {$identity->last_name|escape}<b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li class="dropdown-header">Nav header</li>
                        <li><a href="#">Separated link</a></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>

                <li>
                     <form class="navbar-form" method="post" action="{geturl controller='account' action='logout'}">
                        <button type="submit" class="btn btn-success">Sign out</button>  
                    </form>
                </li>

            </ul>

        {else}
                <form class="navbar-form navbar-right" method="post" action="{geturl controller='account' action='login'}">
                    <div class="form-group">
                        <input type="text" name="username" placeholder="Email" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="password" name="password" placeholder="Password" class="form-control">
                    </div>

                    <input type="hidden" name="redirect" value="/">
                    <button type="submit" class="btn btn-success">Sign in</button>  
                </form>

        {/if}-->

        
        </div><!--/.navbar-collapse -->
      </div>
    </div>

        <div id="content-container" class="column">
            <div id="content">
