<?php echo $this->partial('layout/header', array('authenticated' => $authenticated, 'section' => $section)); ?>
<div class="container">
    <h3><?php echo $full_name ?><br />
        <!--small>A simple, sheek navigation bar style!</small-->
    </h3>
    <br/>
    
    <div class="row">
        <?php echo $this->partial('layout/sidebar', array('authenticated' => $authenticated, 'section' => $section, 'relation_status' => $relation_status, 'uid' => $uid)); ?>
        <div class="col-sm-8 col-sm-offset-0">
            <nav class="nav-sidebar">
                <ul class="nav">
                    <?php foreach($items as $item): ?>
                       <li> 
                            <h3>
                                <a href=<?php echo $item['url']; ?>><?php echo $item['title']; ?></a>
                            </h3>
                            <button id="time-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-time"></i> Created at <?php echo $item['ts']?></button>
                            <button id="time-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-user"></i> by <?php echo $item['user'] ?></button>
                            <br/>
                            <?php echo $item['content'] ?>

                        </li>

                        <button id="like-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-thumbs-up"></i> Like</button>
                        <button id="comment-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-comment"></i> Comment</button>
                        <button id="share-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-share"></i> Share</button>
                        <button id="add-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-user"></i> Add</button>
                        <button id="edit-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-edit"></i> Edit</button>
                        <button id="delete-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-remove"></i> Delete</button>
                       <li class="nav-divider"></li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </div>


    </div>
</div>
<?php echo $this->partial('layout/footer'); ?>


