<?php echo $this->partial('layout/header', array('authenticated' => $authenticated, 'section' => $section)); ?>
<div class="container">
    <h3><?php echo $full_name ?><br />
        <!--small>A simple, sheek navigation bar style!</small-->
    </h3>
    <br/>
    
    <div class="row">
        <div class="col-sm-2">
            <nav class="nav-sidebar">
                <ul class="nav">
                    <li class="active"><a href="/"><i class="glyphicon glyphicon-home"></i> Home</a></li>
                    <li><a href=<?php echo $this->url('blog', array('action' => 'index'))?>><i class="glyphicon glyphicon-briefcase"></i> Projects</a></li>
                    <li><a href=<?php echo $this->url('account') ?>><i class="glyphicon glyphicon-cog"></i> Setting</a></li>
                    <li class="nav-divider"></li>
                    <?php if($authenticated): ?>
                        <li><a href="<?php echo $this->url('account', array('action' => 'logout'))?>"><i class="glyphicon glyphicon-off"></i> Sign out</a></li>
                    <?php else:?>
                        <li><a href="<?php echo $this->url('account', array('action' => 'login'))?>"><i class="glyphicon glyphicon-log-in"></i> Sign in</a></li>
                    <?php endif;?> 
                    <?php if($relation_status == 'owner'): ?>
                    <?php elseif ($relation_status == 'friended'):?>
                        <li class="nav-divider"></li>
                        <button type="submit" uid=<?php echo $uid; ?> id="addfriend-btn" class="btn btn-blog-entry btn-default btn-sm"><i class="glyphicon glyphicon-user"></i> Friend</button>  
                    <?php elseif($relation_status == 'requested'):?>
                        <li class="nav-divider"></li>
                        <button type="submit" uid=<?php echo $uid; ?> id="addfriend-btn" class="btn btn-blog-entry btn-default btn-sm"><i class="glyphicon glyphicon-user"></i> Friend requested</button>  
                    <?php else: ?>
                        <li class="nav-divider"></li>
                        <button type="submit" uid=<?php echo $uid; ?> id="addfriend-btn" class="btn btn-blog-entry btn-default btn-sm"><i class="glyphicon glyphicon-user"></i> <span id="addfriend-btn-text">Add friend</span></button>  

                        <script>
                        $(document).ready(function(){
                            $("#addfriend-btn").click(function(){
                            $.post("/account/friend", {"uid":$(this).attr("uid")})
                                .done(function( data ) {
                                    $("#addfriend-btn-text").text('Friend requested');
                                });
                            });
                        });
                        </script>
                    <?php endif;?> 
                </ul>
            </nav>
        </div>

        <div class="col-sm-8 col-sm-offset-0">
            <nav class="nav-sidebar">
                <ul class="nav">
                    <?php foreach($items as $item): ?>
                       <li> 
                            <h3>
                                <a href=<?php echo $item['url']; ?>><?php echo $item['title']; ?></a>
                            </h3>
                            <button id="time-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-time"></i> Created at <?php echo $item['ts']?></button>
                            <button id="time-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-user"></i> by <?php echo $item['user'] ?></button>
                            <br/>
                            <?php echo $item['content'] ?>

                        </li>

                        <button id="like-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-thumbs-up"></i> Like</button>
                        <button id="comment-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?>><i class="glyphicon glyphicon-comment"></i> Comment</button>
                        <button id="share-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-share"></i> Share</button>
                        <button id="add-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-user"></i> Add</button>
                        <button id="edit-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-edit"></i> Edit</button>
                        <button id="delete-btn" class="btn btn-blog-entry btn-default btn-sm" value=<?php echo $item['post_id']; ?> ><i class="glyphicon glyphicon-remove"></i> Delete</button>
                       <li class="nav-divider"></li>
                    <?php endforeach; ?>
                </ul>
            </nav>
        </div>


    </div>
</div>
<?php echo $this->partial('layout/footer'); ?>


